version: "3.8"

networks:
  adg_network:
    external:
      name: adg-internal

services:
  zookeeper-01:
    container_name: adg-zookeeper-01
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - adg_network
    ports:
      - 22181:2181
    volumes:
      - ./adg-data/zookeeper/adg-zookeeper-01/data:/var/lib/zookeeper/data
      - ./adg-data/zookeeper/adg-zookeeper-01/log:/var/lib/zookeeper/log
  kafka-01:
    container_name: adg-kafka-01
    image: confluentinc/cp-kafka:latest
    hostname: adg-kafka-01
    depends_on:
      - zookeeper-01
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://adg-kafka-01:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_ADVANCED_SESSION-LEAK_THRESHOLD: 12
    networks:
      - adg_network
    volumes:
      - ./adg-data/kafka/adg-kafka-01/data:/var/lib/kafka/data
      - ./adg-data/kafka/adg-kafka-01/config:/etc/kafka
      - ./adg-server/src/main/resources/kafka/kafka-tpch:/etc/enable-trino/kafka-tpch